repos:
  - repo: local
    hooks:
      - id: validate-ai-commit
        name: Validate AI-assisted commit message
        entry: python3 scripts/validate_ai_commit.py
        language: system
        stages: [commit-msg]
        pass_filenames: false
        args: ['.git/COMMIT_EDITMSG']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files