name: Deploy & Install

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run deployment install script
        run: |
          cd deploy
          ./install.sh